// Generated by dts-bundle v0.3.0
// Dependencies for this module:
//   node_modules/review.js/dist/review.js.d.ts
//   node_modules/prh/prh.d.ts

declare module 'reviewjs-prh' {
    import * as ReVIEW from "review.js";
    import * as prh from "prh";
    export class TextValidator implements ReVIEW.Validator {
        config: prh.Config;
        ignoreInlineNames: string[];
        ignoreBlockNames: string[];
        constructor(yamlPath: string);
        start(book: ReVIEW.Book): void;
        checkChunk(chunk: ReVIEW.ContentChunk): void;
    }
}

